<!-- Cabeçalho -->
<br />
<p align="center">

  <h1 align="center">Pré-processamento da Base de Dados</h1>
</p>

## Introdução

A análise de dados somente se torna viável após os dados, em seu estado bruto, serem preparados e válidados para uso. Tal etapa constitui o ponto de partida indispensável para o trabalho de análise de dados, pois permite transformar dados inicialmente desestruturados ou inconsistentes em informações passíveis de exploração analítica.

O pré-processamento envolve um conjunto de procedimentos sistemáticos que incluem a compreensão da natureza dos dados, sua organização, bem como a identificação e o tratamento de inconsistências, tais como valores ausentes, nulos ou discrepantes. Esses procedimentos são conduzidos segundo métodos rigorosos, com o objetivo de assegurar a integridade, a confiabilidade e a qualidade dos dados.

Somente após essa etapa é possível realizar análises consistentes, capazes de gerar insights relevantes que subsidiem, de maneira fundamentada, o processo de tomada de decisão.

## Objetivo

Realizar o carregamento e a adequada estruturação dos dados, de modo a viabilizar sua manipulação e análise. Promover a compreensão aprofundada de suas características, incluindo tipologia, distribuição e possíveis relações entre variáveis.

Proceder à limpeza dos dados, contemplando a identificação e o tratamento de inconsistências, tais como valores ausentes, duplicidades e discrepâncias, com vistas a assegurar sua qualidade e confiabilidade.

Ao final, preparar o conjunto de dados para análises subsequentes, garantindo que esteja consistente, íntegro e apto à extração de informações relevantes.

## Base de dados

**Base de dados:** Pessoas indígenas por localização e situação do domicílio, segundo as Grandes Regiões e Unidades da Federação – Brasil – 2010/2022

**Fonte dos Dados:** [Instituto Brasileiro de Geografia e Estatística – IBGE](https://www.ibge.gov.br/estatisticas/sociais/populacao/22827-censo-demografico-2022.html?edicao=42267&t=resultados)

In [102]:
from pathlib import Path

import pandas as pd

pd.set_option("display.max_columns", None)
pd.set_option("display.float_format", lambda valor: f"{valor:.2f}")

## 1. Carregamento da base de dados

In [103]:
# Considera tanto o diretório atual quanto seus diretórios-pai.
# Assim, o notebook funciona quando o kernel é iniciado na raiz do projeto
# ou dentro do próprio diretório do notebook.
diretorio_atual = Path.cwd().resolve()
ROOT = next(
    (
        caminho
        for caminho in (diretorio_atual, *diretorio_atual.parents)
        if (caminho / "pyproject.toml").exists()
    ),
    None,
)

indigenas_path = (
    ROOT
    / "data"
    / "raw"
    / "indigenas_2010_2022"
    / "indigenas_2010_2022.xlsx"
)

df_indigenas = pd.read_excel(indigenas_path)

## 2. Correção da estrutura da tabela: conversão de colunas de múltiplos níveis para nível único

A presença de colunas organizadas em múltiplos níveis pode gerar inconsistências durante o carregamento dos dados pelo **Pandas**, exigindo tratamentos adicionais para assegurar a interpretação correta e a manipulação eficiente do 

No processo de carregamento do DataFrame, podemos identificar registros que não correspondem a dados válidos, mas que representam **informações descritivas, como nomes de colunas, ou a última linha contendo a fonte dos dados**, oriundos do formato original de múltiplos níveis de colunas.

Pode-se observar que os dados reais começam a partir da **linha 11**, enquanto as linhas anteriores correspondem aos nomes das colunas que foram carregados como registros. Além disso, o rodapé contendo a fonte dos dados gerou uma linha adicional ao final do DataFrame, que também deve ser descartada.  E por fim, podemos observar que as colunas não foram nomeadas pelo carregamento inconsistente ao trazermos os dados para o formato de Dataframe. Podemos constatar ao fazer uma rapida observação nos dados, que embora as colunas não tenha sido nomeadas por conta que seus nomes foram carregadas como linhas,  a ordem das colunas seguem correta, seguindo o organização original da tabela, fazendo com que seja necessário apenas remover as linhas "falsas" e renomear as colunas com suas devidas características.

Esses elementos evidenciam a limitação do **Pandas** em interpretar automaticamente tabelas com colunas multiníveis, sendo necessário realizar um ajuste para remover e ajustar tais registros. O erro de carregamento pode ser observador a segui:

In [104]:
df_indigenas.head(10)

,Censo Demográfico 2022,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13,Unnamed: 14,Unnamed: 15,Unnamed: 16,Unnamed: 17,Unnamed: 18,Unnamed: 19,Unnamed: 20,Unnamed: 21,Unnamed: 22,Unnamed: 23,Unnamed: 24,Unnamed: 25,Unnamed: 26,Unnamed: 27,Unnamed: 28,Unnamed: 29,Unnamed: 30
0,Indígenas: Principais características das pess...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,"Tabela complementar 6 - Pessoas indígenas, por...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Grandes Regiões e Unidades da Federação,Pessoas indígenas,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,NaN,Absoluto,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Percentual (%),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,NaN,2010,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2022,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2010,NaN,NaN,NaN,NaN,NaN,2022,NaN,NaN,NaN,NaN,NaN
7,NaN,Total,Situação do domicílio,NaN,Localização do domicílio,NaN,NaN,NaN,NaN,NaN,Total,Situação do domicílio,NaN,Localização do domicílio,NaN,NaN,NaN,NaN,NaN,Situação do domicílio,NaN,Localização do domicílio,NaN,NaN,NaN,Situação do domicílio,NaN,Localização do domicílio,NaN,NaN,NaN
8,NaN,NaN,NaN,NaN,Em Terras Indígenas,NaN,NaN,Fora Terras Indígenas,NaN,NaN,NaN,NaN,NaN,Em Terras Indígenas,NaN,NaN,Fora Terras Indígenas,NaN,NaN,NaN,NaN,Em Terras Indígenas,NaN,Fora Terras Indígenas,NaN,NaN,NaN,Em Terras Indígenas,NaN,Fora Terras Indígenas,NaN
9,NaN,NaN,NaN,NaN,Total,Situação do domicílio,NaN,Total,Situação do domicílio,NaN,NaN,NaN,NaN,Total,Situação do domicílio,NaN,Total,Situação do domicílio,NaN,NaN,NaN,Situação do domicílio,NaN,Situação do domicílio,NaN,NaN,NaN,Situação do domicílio,NaN,Situação do domicílio,NaN

In [105]:
df_indigenas.tail(5)

,Censo Demográfico 2022,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13,Unnamed: 14,Unnamed: 15,Unnamed: 16,Unnamed: 17,Unnamed: 18,Unnamed: 19,Unnamed: 20,Unnamed: 21,Unnamed: 22,Unnamed: 23,Unnamed: 24,Unnamed: 25,Unnamed: 26,Unnamed: 27,Unnamed: 28,Unnamed: 29,Unnamed: 30
40,Mato Grosso do Sul,77025,14894,62131,61158,1645,59513,15867,13249,2618,116469,41861,74608,68682,1423,67259,47787,40438,7349,19.34,80.66,2.69,97.31,83.50,16.50,35.94,64.06,2.07,97.93,84.62,15.38
41,Mato Grosso,51696,6291,45405,42525,629,41896,9171,5662,3509,58356,10117,48239,45175,242,44933,13181,9875,3306,12.17,87.83,1.48,98.52,61.74,38.26,17.34,82.66,0.54,99.46,74.92,25.08
42,Goiás,8583,8030,553,336,105,231,8247,7925,322,19517,18643,874,344,106,238,19173,18537,636,93.56,6.44,31.25,68.75,96.10,3.90,95.52,4.48,30.81,69.19,96.68,3.32
43,Distrito Federal,6128,5941,187,-,-,-,6128,5941,187,5811,5337,474,-,-,-,5811,5337,474,96.95,3.05,-,-,96.95,3.05,91.84,8.16,-,-,91.84,8.16
44,"Fonte: IBGE, Censo Demográfico 2022.",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

### Ajuste dos nomes das colunas

Para reorganizar o DataFrame em um formato adequado, torna-se necessário ajustar os nomes originais das colunas, que estão estruturados em múltiplos níveis de cabeçalho, refletindo a hierarquia presente na planilha de origem. Esse formato dificulta o carregamento correto dos dados no **Pandas**, uma vez que os nomes das colunas não estão em um único nível, gerando linhas com valores nulos e impedindo a identificação e manipulação adequada dos campos.

A solução consiste na **normalização dos nomes das colunas**, transformando a estrutura em um **único nível de cabeçalho** e padronizando os nomes de maneira clara e consistente. Cada coluna passa a possuir um título direto e conciso, preservando sua identidade e significado, mas adequado para análise em Python/**Pandas**.

Esse procedimento permite a leitura correta do DataFrame, viabilizando análises exploratórias, cruzamentos e visualizações a partir de um esquema de dados limpo e funcional. O processo gera uma nova linha de cabeçalho com os nomes ajustados das colunas.

#### Dicionário de variáveis reorganizado e padronizado – População Indígena (2010 e 2022)

| Coluna                                | Descrição |
|---------------------------------------|-----------|
| **Localidade**                                | Unidade da Federação (Estado ou Região do Brasil) e o estado Brasileiro. |
| **Indígenas 2010 Total**              | Total de pessoas indígenas em 2010, considerando todos os domicílios. |
| **Indígenas 2010 Urbano**             | Número de indígenas em domicílios localizados em áreas urbanas em 2010. |
| **Indígenas 2010 Rural**              | Número de indígenas em domicílios localizados em áreas rurais em 2010. |
| **Indígenas 2010 TI Total**           | Total de indígenas residentes em Terras Indígenas (TIs) em 2010. |
| **Indígenas 2010 TI Urbano**          | Indígenas em áreas urbanas dentro de Terras Indígenas em 2010. |
| **Indígenas 2010 TI Rural**           | Indígenas em áreas rurais dentro de Terras Indígenas em 2010. |
| **Indígenas 2010 Fora TI Total**      | Total de indígenas fora de Terras Indígenas em 2010. |
| **Indígenas 2010 Fora TI Urbano**     | Indígenas fora de TIs e em áreas urbanas em 2010. |
| **Indígenas 2010 Fora TI Rural**      | Indígenas fora de TIs e em áreas rurais em 2010. |
| **Indígenas 2022 Total**              | Total de pessoas indígenas em 2022, considerando todos os domicílios. |
| **Indígenas 2022 Urbano**             | Número de indígenas em áreas urbanas em 2022. |
| **Indígenas 2022 Rural**              | Número de indígenas em áreas rurais em 2022. |
| **Indígenas 2022 TI Total**           | Total de indígenas residentes em Terras Indígenas em 2022. |
| **Indígenas 2022 TI Urbano**          | Indígenas em áreas urbanas dentro de TIs em 2022. |
| **Indígenas 2022 TI Rural**           | Indígenas em áreas rurais dentro de TIs em 2022. |
| **Indígenas 2022 Fora TI Total**      | Total de indígenas fora de Terras Indígenas em 2022. |
| **Indígenas 2022 Fora TI Urbano**     | Indígenas fora de TIs e em áreas urbanas em 2022. |
| **Indígenas 2022 Fora TI Rural**      | Indígenas fora de TIs e em áreas rurais em 2022. |
| **% Indígenas 2010 Urbano**           | Percentual da população indígena em áreas urbanas em 2010. |
| **% Indígenas 2010 Rural**            | Percentual da população indígena em áreas rurais em 2010. |
| **% Indígenas 2010 TI Urbano**        | Percentual de indígenas em áreas urbanas dentro de TIs em 2010. |
| **% Indígenas 2010 TI Rural**         | Percentual de indígenas em áreas rurais dentro de TIs em 2010. |
| **% Indígenas 2010 Fora TI Urbano**   | Percentual de indígenas fora de TIs em áreas urbanas em 2010. |
| **% Indígenas 2010 Fora TI Rural**    | Percentual de indígenas fora de TIs em áreas rurais em 2010. |
| **% Indígenas 2022 Urbano**           | Percentual da população indígena em áreas urbanas em 2022. |
| **% Indígenas 2022 Rural**            | Percentual da população indígena em áreas rurais em 2022. |
| **% Indígenas 2022 TI Urbano**        | Percentual de indígenas em áreas urbanas dentro de TIs em 2022. |
| **% Indígenas 2022 TI Rural**         | Percentual de indígenas em áreas rurais dentro de TIs em 2022. |
| **% Indígenas 2022 Fora TI Urbano**   | Percentual de indígenas fora de TIs em áreas urbanas em 2022. |
| **% Indígenas 2022 Fora TI Rural**    | Percentual de indígenas fora de TIs em áreas rurais em 2022. |

#### Aplicando ajustes:

In [106]:
nomes_colunas_padronizados = [
    'Localidade',
    'Indígenas 2010 Total',
    'Indígenas 2010 Urbano',
    'Indígenas 2010 Rural',
    'Indígenas 2010 TI Total',
    'Indígenas 2010 TI Urbano',
    'Indígenas 2010 TI Rural',
    'Indígenas 2010 Fora TI Total',
    'Indígenas 2010 Fora TI Urbano',
    'Indígenas 2010 Fora TI Rural',
    'Indígenas 2022 Total',
    'Indígenas 2022 Urbano',
    'Indígenas 2022 Rural',
    'Indígenas 2022 TI Total',
    'Indígenas 2022 TI Urbano',
    'Indígenas 2022 TI Rural',
    'Indígenas 2022 Fora TI Total',
    'Indígenas 2022 Fora TI Urbano',
    'Indígenas 2022 Fora TI Rural',
    '% Indígenas 2010 Urbano',
    '% Indígenas 2010 Rural',
    '% Indígenas 2010 TI Urbano',
    '% Indígenas 2010 TI Rural',
    '% Indígenas 2010 Fora TI Urbano',
    '% Indígenas 2010 Fora TI Rural',
    '% Indígenas 2022 Urbano',
    '% Indígenas 2022 Rural',
    '% Indígenas 2022 TI Urbano',
    '% Indígenas 2022 TI Rural',
    '% Indígenas 2022 Fora TI Urbano',
    '% Indígenas 2022 Fora TI Rural'
]

df_indigenas.columns = nomes_colunas_padronizados

Pode-se observar, examinando apenas a coluna "Localidade", os seguintes registros:

- Indígenas: Principais características das pessoas e dos domicílios, por situação urbana ou rural do domicílio - Resultados do Universo
- Tabela complementar 6 - Pessoas indígenas, por localização e situação do domicílio, segundo as Grandes Regiões e as Unidades da Federação - Brasil - 2010/2022
- Grandes Regiões e Unidades da Federação
- Fonte: IBGE, Censo Demográfico 2022.

Como concluído anteriormente, essas informações foram geradas durante a conversão incorreta do arquivo original para o formato de DataFrame do **Pandas**, criando 12 linhas com valores nulos que representam os nomes originais das colunas, incluindo a última linha do rodapé com a fonte. Tal comportamento pode ser confirmado ao comparar os registros com a tabela original.

Ao confrontar os dados com a tabela original, observa-se que os dados efetivos do carregamento começam na **linha 11** e se estendem até a **linha 43**:

$$
\text{Quantidade de linhas com dados reais} = (43 - 11) + 1 = 33
$$

Portanto, o DataFrame possui **45 linhas no total**, sendo apenas **33 referentes a dados válidos**. As **12 linhas restantes** correspondem a registros falsos oriundos dos nomes originais das colunas e do rodapé da fonte, que foram carregados como linhas com valores nulos ou com os próprios nomes das colunas. É, portanto, necessário remover essas linhas para assegurar a consistência e a integridade da análise.

In [107]:
df_indigenas.head(12) # Mostra as primeiras 12 linhas com os novos nomes das colunas

,Localidade,Indígenas 2010 Total,Indígenas 2010 Urbano,Indígenas 2010 Rural,Indígenas 2010 TI Total,Indígenas 2010 TI Urbano,Indígenas 2010 TI Rural,Indígenas 2010 Fora TI Total,Indígenas 2010 Fora TI Urbano,Indígenas 2010 Fora TI Rural,Indígenas 2022 Total,Indígenas 2022 Urbano,Indígenas 2022 Rural,Indígenas 2022 TI Total,Indígenas 2022 TI Urbano,Indígenas 2022 TI Rural,Indígenas 2022 Fora TI Total,Indígenas 2022 Fora TI Urbano,Indígenas 2022 Fora TI Rural,% Indígenas 2010 Urbano,% Indígenas 2010 Rural,% Indígenas 2010 TI Urbano,% Indígenas 2010 TI Rural,% Indígenas 2010 Fora TI Urbano,% Indígenas 2010 Fora TI Rural,% Indígenas 2022 Urbano,% Indígenas 2022 Rural,% Indígenas 2022 TI Urbano,% Indígenas 2022 TI Rural,% Indígenas 2022 Fora TI Urbano,% Indígenas 2022 Fora TI Rural
0,Indígenas: Principais características das pess...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,"Tabela complementar 6 - Pessoas indígenas, por...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Grandes Regiões e Unidades da Federação,Pessoas indígenas,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,NaN,Absoluto,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Percentual (%),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,NaN,2010,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2022,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2010,NaN,NaN,NaN,NaN,NaN,2022,NaN,NaN,NaN,NaN,NaN
7,NaN,Total,Situação do domicílio,NaN,Localização do domicílio,NaN,NaN,NaN,NaN,NaN,Total,Situação do domicílio,NaN,Localização do domicílio,NaN,NaN,NaN,NaN,NaN,Situação do domicílio,NaN,Localização do domicílio,NaN,NaN,NaN,Situação do domicílio,NaN,Localização do domicílio,NaN,NaN,NaN
8,NaN,NaN,NaN,NaN,Em Terras Indígenas,NaN,NaN,Fora Terras Indígenas,NaN,NaN,NaN,NaN,NaN,Em Terras Indígenas,NaN,NaN,Fora Terras Indígenas,NaN,NaN,NaN,NaN,Em Terras Indígenas,NaN,Fora Terras Indígenas,NaN,NaN,NaN,Em Terras Indígenas,NaN,Fora Terras Indígenas,NaN
9,NaN,NaN,NaN,NaN,Total,Situação do domicílio,NaN,Total,Situação do domicílio,NaN,NaN,NaN,NaN,Total,Situação do domicílio,NaN,Total,Situação do domicílio,NaN,NaN,NaN,Situação do domicílio,NaN,Situação do domicílio,NaN,NaN,NaN,Situação do domicílio,NaN,Situação do domicílio,NaN
10,NaN,NaN,Urbana,Rural,NaN,Urbana,Rural,NaN,Urbana,Rural,NaN,Urbana,Rural,NaN,Urbana,Rural,NaN,Urbana,Rural,Urbana,Rural,Urbana,Rural,Urbana,Rural,Urbana,Rural,Urbana,Rural,Urbana,Rural
11,Brasil,896917,324834,572083,517383,25963,491420,379534,298871,80663,1694836,914746,780090,622844,69986,552858,1071992,844760,227232,36.22,63.78,5.02,94.98,78.75,21.25,53.97,46.03,11.24,88.76,78.80,21.20

#### Remoção das linhas "falsas"

In [108]:
# Após indentificada cada linha "falsa" por seus respectivos índices.
# Criaremos uma lista de índices para remover.
# Referente as 11 primeiras linhas e a última.
indices_para_remover = list(range(11)) + [44]
print("Índices para remover: ", indices_para_remover)

# Remover do DataFrame as linhas 
df_indigenas = df_indigenas.drop(indices_para_remover)
print("Índices removidos.")

# Renumerar índices das linhas que restaram
df_indigenas = df_indigenas.reset_index(drop=True)
print("Índices renumerados.")

Índices para remover:  [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 44]
Índices removidos.
Índices renumerados.

#### Verificacão após remoção dos elementos inconsitentes

Pode-se observar que os dados encontram-se agora organizados de forma adequada, com uma hierarquia consistente para os nomes das colunas, e que as linhas "falsas" anteriormente carregadas foram devidamente removidas.

In [109]:
df_indigenas.head(10) # Mostras as primeiras 10 linhas do DataFrame após a remoção das linhas indesejadas

,Localidade,Indígenas 2010 Total,Indígenas 2010 Urbano,Indígenas 2010 Rural,Indígenas 2010 TI Total,Indígenas 2010 TI Urbano,Indígenas 2010 TI Rural,Indígenas 2010 Fora TI Total,Indígenas 2010 Fora TI Urbano,Indígenas 2010 Fora TI Rural,Indígenas 2022 Total,Indígenas 2022 Urbano,Indígenas 2022 Rural,Indígenas 2022 TI Total,Indígenas 2022 TI Urbano,Indígenas 2022 TI Rural,Indígenas 2022 Fora TI Total,Indígenas 2022 Fora TI Urbano,Indígenas 2022 Fora TI Rural,% Indígenas 2010 Urbano,% Indígenas 2010 Rural,% Indígenas 2010 TI Urbano,% Indígenas 2010 TI Rural,% Indígenas 2010 Fora TI Urbano,% Indígenas 2010 Fora TI Rural,% Indígenas 2022 Urbano,% Indígenas 2022 Rural,% Indígenas 2022 TI Urbano,% Indígenas 2022 TI Rural,% Indígenas 2022 Fora TI Urbano,% Indígenas 2022 Fora TI Rural
0,Brasil,896917,324834,572083,517383,25963,491420,379534,298871,80663,1694836,914746,780090,622844,69986,552858,1071992,844760,227232,36.22,63.78,5.02,94.98,78.75,21.25,53.97,46.03,11.24,88.76,78.80,21.20
1,Norte,342836,61565,281271,251891,2179,249712,90945,59386,31559,753780,376875,376905,316827,34974,281853,436953,341901,95052,17.96,82.04,0.87,99.13,65.30,34.70,50.00,50.00,11.04,88.96,78.25,21.75
2,Rondônia,13076,2906,10170,9217,-,9217,3859,2906,953,21146,8094,13052,11525,-,11525,9621,8094,1527,22.22,77.78,-,100,75.30,24.70,38.28,61.72,-,100,84.13,15.87
3,Acre,17578,2595,14983,13308,-,13308,4270,2595,1675,31694,8849,22845,19583,-,19583,12111,8849,3262,14.76,85.24,-,100,60.77,39.23,27.92,72.08,-,100,73.07,26.93
4,Amazonas,183514,34316,149198,129529,1230,128299,53985,33086,20899,490935,305866,185069,149080,33070,116010,341855,272796,69059,18.70,81.30,0.95,99.05,61.29,38.71,62.30,37.70,22.18,77.82,79.80,20.20
5,Roraima,55922,8243,47679,46505,949,45556,9417,7294,2123,97668,21674,75994,71754,1544,70210,25914,20130,5784,14.74,85.26,2.04,97.96,77.46,22.54,22.19,77.81,2.15,97.85,77.68,22.32
6,Pará,51217,9966,41251,35816,-,35816,15401,9966,5435,80980,25338,55642,41819,360,41459,39161,24978,14183,19.46,80.54,-,100,64.71,35.29,31.29,68.71,0.86,99.14,63.78,36.22
7,Amapá,7411,1360,6051,5956,-,5956,1455,1360,95,11334,2859,8475,7853,-,7853,3481,2859,622,18.35,81.65,-,100,93.47,6.53,25.22,74.78,-,100,82.13,17.87
8,Tocantins,14118,2179,11939,11560,-,11560,2558,2179,379,20023,4195,15828,15213,-,15213,4810,4195,615,15.43,84.57,-,100,85.18,14.82,20.95,79.05,-,100,87.21,12.79
9,Nordeste,232739,114401,118338,106142,19159,86983,126597,95242,31355,529128,329639,199489,129882,30200,99682,399246,299439,99807,49.15,50.85,18.05,81.95,75.23,24.77,62.30,37.70,23.25,76.75,75.00,25.00

In [110]:
df_indigenas.tail(5) # Mostra as últimas 5 linhas

,Localidade,Indígenas 2010 Total,Indígenas 2010 Urbano,Indígenas 2010 Rural,Indígenas 2010 TI Total,Indígenas 2010 TI Urbano,Indígenas 2010 TI Rural,Indígenas 2010 Fora TI Total,Indígenas 2010 Fora TI Urbano,Indígenas 2010 Fora TI Rural,Indígenas 2022 Total,Indígenas 2022 Urbano,Indígenas 2022 Rural,Indígenas 2022 TI Total,Indígenas 2022 TI Urbano,Indígenas 2022 TI Rural,Indígenas 2022 Fora TI Total,Indígenas 2022 Fora TI Urbano,Indígenas 2022 Fora TI Rural,% Indígenas 2010 Urbano,% Indígenas 2010 Rural,% Indígenas 2010 TI Urbano,% Indígenas 2010 TI Rural,% Indígenas 2010 Fora TI Urbano,% Indígenas 2010 Fora TI Rural,% Indígenas 2022 Urbano,% Indígenas 2022 Rural,% Indígenas 2022 TI Urbano,% Indígenas 2022 TI Rural,% Indígenas 2022 Fora TI Urbano,% Indígenas 2022 Fora TI Rural
28,Centro-Oeste,143432,35156,108276,104019,2379,101640,39413,32777,6636,200153,75958,124195,114201,1771,112430,85952,74187,11765,24.51,75.49,2.29,97.71,83.16,16.84,37.95,62.05,1.55,98.45,86.31,13.69
29,Mato Grosso do Sul,77025,14894,62131,61158,1645,59513,15867,13249,2618,116469,41861,74608,68682,1423,67259,47787,40438,7349,19.34,80.66,2.69,97.31,83.50,16.50,35.94,64.06,2.07,97.93,84.62,15.38
30,Mato Grosso,51696,6291,45405,42525,629,41896,9171,5662,3509,58356,10117,48239,45175,242,44933,13181,9875,3306,12.17,87.83,1.48,98.52,61.74,38.26,17.34,82.66,0.54,99.46,74.92,25.08
31,Goiás,8583,8030,553,336,105,231,8247,7925,322,19517,18643,874,344,106,238,19173,18537,636,93.56,6.44,31.25,68.75,96.10,3.90,95.52,4.48,30.81,69.19,96.68,3.32
32,Distrito Federal,6128,5941,187,-,-,-,6128,5941,187,5811,5337,474,-,-,-,5811,5337,474,96.95,3.05,-,-,96.95,3.05,91.84,8.16,-,-,91.84,8.16

In [111]:
df_indigenas['Localidade'].unique() # Verificar valores únicos na coluna 'Localidade'

array(['Brasil', 'Norte', 'Rondônia', 'Acre', 'Amazonas', 'Roraima',
       'Pará', 'Amapá', 'Tocantins', 'Nordeste', 'Maranhão', 'Piauí',
       'Ceará', 'Rio Grande do Norte', 'Paraíba', 'Pernambuco', 'Alagoas',
       'Sergipe', 'Bahia', 'Sudeste', 'Minas Gerais', 'Espírito Santo',
       'Rio de Janeiro', 'São Paulo', 'Sul', 'Paraná', 'Santa Catarina',
       'Rio Grande do Sul', 'Centro-Oeste', 'Mato Grosso do Sul',
       'Mato Grosso', 'Goiás', 'Distrito Federal'], dtype=object)

## 3 Análise de qualidade

Nesta seção, procede-se à avaliação da integridade e consistência do conjunto de dados, com o objetivo de identificar possíveis anomalias, valores ausentes, duplicidades e inconsistências estruturais. Tal análise constitui etapa essencial do processo de preparação dos dados, uma vez que a confiabilidade das inferências subsequentes depende diretamente da qualidade do material empírico disponível.

Nesta etapa, é possível carregar aleatoriamente cinco linhas do DataFrame para visualizar os dados. Recomenda-se executar esta célula diversas vezes, a fim de obter uma melhor compreensão dos dados e de suas inconsistências, sem a necessidade de imprimir o DataFrame completo.

In [112]:
df_indigenas.sample(5) # Mostra 5 linhas aleatórias do DataFrame

,Localidade,Indígenas 2010 Total,Indígenas 2010 Urbano,Indígenas 2010 Rural,Indígenas 2010 TI Total,Indígenas 2010 TI Urbano,Indígenas 2010 TI Rural,Indígenas 2010 Fora TI Total,Indígenas 2010 Fora TI Urbano,Indígenas 2010 Fora TI Rural,Indígenas 2022 Total,Indígenas 2022 Urbano,Indígenas 2022 Rural,Indígenas 2022 TI Total,Indígenas 2022 TI Urbano,Indígenas 2022 TI Rural,Indígenas 2022 Fora TI Total,Indígenas 2022 Fora TI Urbano,Indígenas 2022 Fora TI Rural,% Indígenas 2010 Urbano,% Indígenas 2010 Rural,% Indígenas 2010 TI Urbano,% Indígenas 2010 TI Rural,% Indígenas 2010 Fora TI Urbano,% Indígenas 2010 Fora TI Rural,% Indígenas 2022 Urbano,% Indígenas 2022 Rural,% Indígenas 2022 TI Urbano,% Indígenas 2022 TI Rural,% Indígenas 2022 Fora TI Urbano,% Indígenas 2022 Fora TI Rural
13,Rio Grande do Norte,2597,2080,517,-,-,-,2597,2080,517,11724,5390,6334,-,-,-,11724,5390,6334,80.09,19.91,-,-,80.09,19.91,45.97,54.03,-,-,45.97,54.03
9,Nordeste,232739,114401,118338,106142,19159,86983,126597,95242,31355,529128,329639,199489,129882,30200,99682,399246,299439,99807,49.15,50.85,18.05,81.95,75.23,24.77,62.30,37.70,23.25,76.75,75.00,25.00
29,Mato Grosso do Sul,77025,14894,62131,61158,1645,59513,15867,13249,2618,116469,41861,74608,68682,1423,67259,47787,40438,7349,19.34,80.66,2.69,97.31,83.50,16.50,35.94,64.06,2.07,97.93,84.62,15.38
19,Sudeste,99137,79272,19865,15904,652,15252,83233,78620,4613,123434,95348,28086,21525,1740,19785,101909,93608,8301,79.96,20.04,4.10,95.90,94.46,5.54,77.25,22.75,8.08,91.92,91.85,8.15
30,Mato Grosso,51696,6291,45405,42525,629,41896,9171,5662,3509,58356,10117,48239,45175,242,44933,13181,9875,3306,12.17,87.83,1.48,98.52,61.74,38.26,17.34,82.66,0.54,99.46,74.92,25.08

### Resumo estatístico: tipos, valores nulos, unicidade e contagem de registros
O resumo estatístico apresentado fornece uma visão abrangente da estrutura do DataFrame, incluindo os tipos de dados de cada coluna, a presença de valores nulos, a quantidade de valores únicos, o percentual de unicidade e o total de registros. Esses indicadores permitem identificar inconsistências, redundâncias e padrões nos dados, servindo como base para o pré-processamento e para análises subsequentes.

In [113]:
summary = pd.DataFrame({
    "dtype": df_indigenas.dtypes,
    "n_unique": df_indigenas.nunique(),
    "n_null": df_indigenas.isnull().sum(),
    "%_unique": (df_indigenas.nunique() / len(df_indigenas) * 100).round(2),
    "%_null": (df_indigenas.isnull().mean() * 100).round(2),
    "total_rows": len(df_indigenas)
})

summary

,dtype,n_unique,n_null,%_unique,%_null,total_rows
Localidade,object,33,0,100.00,0.00,33
Indígenas 2010 Total,object,33,0,100.00,0.00,33
Indígenas 2010 Urbano,object,33,0,100.00,0.00,33
Indígenas 2010 Rural,object,33,0,100.00,0.00,33
Indígenas 2010 TI Total,object,31,0,93.94,0.00,33
Indígenas 2010 TI Urbano,object,21,0,63.64,0.00,33
Indígenas 2010 TI Rural,object,31,0,93.94,0.00,33
Indígenas 2010 Fora TI Total,object,33,0,100.00,0.00,33
Indígenas 2010 Fora TI Urbano,object,33,0,100.00,0.00,33
Indígenas 2010 Fora TI Rural,object,33,0,100.00,0.00,33
Indígenas 2022 Total,object,33,0,100.00,0.00,33
Indígenas 2022 Urbano,object,33,0,100.00,0.00,33
Indígenas 2022 Rural,object,33,0,100.00,0.00,33
Indígenas 2022 TI Total,object,32,0,96.97,0.00,33
Indígenas 2022 TI Urbano,object,23,0,69.70,0.00,33
Indígenas 2022 TI Rural,object,32,0,96.97,0.00,33
Indígenas 2022 Fora TI Total,object,33,0,100.00,0.00,33
Indígenas 2022 Fora TI Urbano,object,33,0,100.00,0.00,33
Indígenas 2022 Fora TI Rural,object,33,0,100.00,0.00,33
% Indígenas 2010 Urbano,object,33,0,100.00,0.00,33
% Indígenas 2010 Rural,object,33,0,100.00,0.00,33
% Indígenas 2010 TI Urbano,object,21,0,63.64,0.00,33
% Indígenas 2010 TI Rural,object,22,0,66.67,0.00,33
% Indígenas 2010 Fora TI Urbano,object,33,0,100.00,0.00,33
% Indígenas 2010 Fora TI Rural,object,33,0,100.00,0.00,33
% Indígenas 2022 Urbano,object,33,0,100.00,0.00,33
% Indígenas 2022 Rural,object,33,0,100.00,0.00,33
% Indígenas 2022 TI Urbano,object,23,0,69.70,0.00,33
% Indígenas 2022 TI Rural,object,24,0,72.73,0.00,33
% Indígenas 2022 Fora TI Urbano,object,33,0,100.00,0.00,33
% Indígenas 2022 Fora TI Rural,object,33,0,100.00,0.00,33

### Tipo de dados incorretos

Constata-se uma inconsistência significativa nos dados, mesmo após a padronização da hierarquia de múltiplos níveis de colunas para um formato de coluna única. Observa-se que os campos que deveriam conter valores numéricos encontram-se no formato `object`, indicando a necessidade de conversão adequada para permitir análises quantitativas precisas.

Com exceção da coluna **Localidade**, todas as demais correspondem a atributos de natureza quantitativa. Assim, é necessário converter essas colunas para tipos numéricos, viabilizando a realização de análises estatísticas e comparativas de forma consistente e confiável.

Adicionalmente, de acordo com a descrição do **metadado do censo** sobre as características dos dados analisados, o símbolo `"-"` representa um valor absoluto igual a zero, e não um valor nulo ou ausente. Portanto, nos locais onde os dados estão representados dessa forma, deve-se substituir o símbolo por `0` em formato numérico, refletindo corretamente a ausência de indivíduos indígenas nessas localidades.

In [114]:
colunas_para_converter = df_indigenas.columns.difference(['Localidade']) # Seleciona todas as colunas exceto 'Localidade'

df_indigenas[colunas_para_converter] = df_indigenas[colunas_para_converter].replace('-', 0) # Substitui "-" por 0

df_indigenas[colunas_para_converter] = df_indigenas[colunas_para_converter].apply(pd.to_numeric, errors='coerce') # Converte para numérico

/tmp/ipykernel_48090/1501892695.py:3: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df_indigenas[colunas_para_converter] = df_indigenas[colunas_para_converter].replace('-', 0) # Substitui "-" por 0

### Resumo estatístico atualizado: tipos, valores nulos, unicidade e contagem de registros

Pode-se observar que, após a conversão adequada, todos os campos quantitativos do DataFrame estão agora no tipo numérico correto, garantindo consistência e precisão para a realização de análises estatísticas e comparativas.

In [115]:
summary = pd.DataFrame({
    "dtype": df_indigenas.dtypes,
    "n_unique": df_indigenas.nunique(),
    "n_null": df_indigenas.isnull().sum(),
    "%_unique": (df_indigenas.nunique() / len(df_indigenas) * 100).round(2),
    "%_null": (df_indigenas.isnull().mean() * 100).round(2),
    "total_rows": len(df_indigenas)
})

summary

,dtype,n_unique,n_null,%_unique,%_null,total_rows
Localidade,object,33,0,100.00,0.00,33
Indígenas 2010 Total,int64,33,0,100.00,0.00,33
Indígenas 2010 Urbano,int64,33,0,100.00,0.00,33
Indígenas 2010 Rural,int64,33,0,100.00,0.00,33
Indígenas 2010 TI Total,int64,31,0,93.94,0.00,33
Indígenas 2010 TI Urbano,int64,21,0,63.64,0.00,33
Indígenas 2010 TI Rural,int64,31,0,93.94,0.00,33
Indígenas 2010 Fora TI Total,int64,33,0,100.00,0.00,33
Indígenas 2010 Fora TI Urbano,int64,33,0,100.00,0.00,33
Indígenas 2010 Fora TI Rural,int64,33,0,100.00,0.00,33
Indígenas 2022 Total,int64,33,0,100.00,0.00,33
Indígenas 2022 Urbano,int64,33,0,100.00,0.00,33
Indígenas 2022 Rural,int64,33,0,100.00,0.00,33
Indígenas 2022 TI Total,int64,32,0,96.97,0.00,33
Indígenas 2022 TI Urbano,int64,23,0,69.70,0.00,33
Indígenas 2022 TI Rural,int64,32,0,96.97,0.00,33
Indígenas 2022 Fora TI Total,int64,33,0,100.00,0.00,33
Indígenas 2022 Fora TI Urbano,int64,33,0,100.00,0.00,33
Indígenas 2022 Fora TI Rural,int64,33,0,100.00,0.00,33
% Indígenas 2010 Urbano,float64,33,0,100.00,0.00,33
% Indígenas 2010 Rural,float64,33,0,100.00,0.00,33
% Indígenas 2010 TI Urbano,float64,21,0,63.64,0.00,33
% Indígenas 2010 TI Rural,float64,22,0,66.67,0.00,33
% Indígenas 2010 Fora TI Urbano,float64,33,0,100.00,0.00,33
% Indígenas 2010 Fora TI Rural,float64,33,0,100.00,0.00,33
% Indígenas 2022 Urbano,float64,33,0,100.00,0.00,33
% Indígenas 2022 Rural,float64,33,0,100.00,0.00,33
% Indígenas 2022 TI Urbano,float64,23,0,69.70,0.00,33
% Indígenas 2022 TI Rural,float64,24,0,72.73,0.00,33
% Indígenas 2022 Fora TI Urbano,float64,33,0,100.00,0.00,33
% Indígenas 2022 Fora TI Rural,float64,33,0,100.00,0.00,33

In [116]:
df_indigenas.sample(5) # Mostra 5 linhas aleatórias do DataFrame após a conversão para numérico

,Localidade,Indígenas 2010 Total,Indígenas 2010 Urbano,Indígenas 2010 Rural,Indígenas 2010 TI Total,Indígenas 2010 TI Urbano,Indígenas 2010 TI Rural,Indígenas 2010 Fora TI Total,Indígenas 2010 Fora TI Urbano,Indígenas 2010 Fora TI Rural,Indígenas 2022 Total,Indígenas 2022 Urbano,Indígenas 2022 Rural,Indígenas 2022 TI Total,Indígenas 2022 TI Urbano,Indígenas 2022 TI Rural,Indígenas 2022 Fora TI Total,Indígenas 2022 Fora TI Urbano,Indígenas 2022 Fora TI Rural,% Indígenas 2010 Urbano,% Indígenas 2010 Rural,% Indígenas 2010 TI Urbano,% Indígenas 2010 TI Rural,% Indígenas 2010 Fora TI Urbano,% Indígenas 2010 Fora TI Rural,% Indígenas 2022 Urbano,% Indígenas 2022 Rural,% Indígenas 2022 TI Urbano,% Indígenas 2022 TI Rural,% Indígenas 2022 Fora TI Urbano,% Indígenas 2022 Fora TI Rural
0,Brasil,896917,324834,572083,517383,25963,491420,379534,298871,80663,1694836,914746,780090,622844,69986,552858,1071992,844760,227232,36.22,63.78,5.02,94.98,78.75,21.25,53.97,46.03,11.24,88.76,78.80,21.20
28,Centro-Oeste,143432,35156,108276,104019,2379,101640,39413,32777,6636,200153,75958,124195,114201,1771,112430,85952,74187,11765,24.51,75.49,2.29,97.71,83.16,16.84,37.95,62.05,1.55,98.45,86.31,13.69
32,Distrito Federal,6128,5941,187,0,0,0,6128,5941,187,5811,5337,474,0,0,0,5811,5337,474,96.95,3.05,0.00,0.00,96.95,3.05,91.84,8.16,0.00,0.00,91.84,8.16
7,Amapá,7411,1360,6051,5956,0,5956,1455,1360,95,11334,2859,8475,7853,0,7853,3481,2859,622,18.35,81.65,0.00,100.00,93.47,6.53,25.22,74.78,0.00,100.00,82.13,17.87
14,Paraíba,25043,13721,11322,18296,7426,10870,6747,6295,452,30140,16991,13149,19044,6721,12323,11096,10270,826,54.79,45.21,40.59,59.41,93.30,6.70,56.37,43.63,35.29,64.71,92.56,7.44

## Dividindo a base de dados por país, regiões, e estados

Dividir a base de dados por País, Regiões e Estados permite organizar os dados de maneira hierárquica e segmentada, facilitando análises específicas em diferentes níveis geográficos. Essa abordagem contribui para a clareza e precisão das análises, possibilitando a identificação de padrões regionais, comparações entre unidades federativas e uma exploração mais eficiente dos dados, sem a necessidade de processar o conjunto completo a cada análise.

In [117]:
# País
df_indigenas_pais = df_indigenas[df_indigenas["Localidade"] == "Brasil"]

# Regiões
regioes = ["Norte", "Nordeste", "Sudeste", "Sul", "Centro-Oeste"]
df_indigenas_regioes = df_indigenas[df_indigenas["Localidade"].isin(regioes)]

# Estados
df_indigenas_estados = df_indigenas[~df_indigenas["Localidade"].isin(["Brasil"] + regioes)]

In [118]:
df_indigenas_pais['Localidade'].unique() # Verificar valores únicos na coluna 'Localidade' do DataFrame df_indigenas_pais

array(['Brasil'], dtype=object)

In [119]:
df_indigenas_regioes['Localidade'].unique() # Verificar valores únicos na coluna 'Localidade' do DataFrame df_indigenas_regioes

array(['Norte', 'Nordeste', 'Sudeste', 'Sul', 'Centro-Oeste'],
      dtype=object)

In [120]:
df_indigenas_estados['Localidade'].unique() # Verificar valores únicos na coluna 'Localidade' do DataFrame df_indigenas_estados

array(['Rondônia', 'Acre', 'Amazonas', 'Roraima', 'Pará', 'Amapá',
       'Tocantins', 'Maranhão', 'Piauí', 'Ceará', 'Rio Grande do Norte',
       'Paraíba', 'Pernambuco', 'Alagoas', 'Sergipe', 'Bahia',
       'Minas Gerais', 'Espírito Santo', 'Rio de Janeiro', 'São Paulo',
       'Paraná', 'Santa Catarina', 'Rio Grande do Sul',
       'Mato Grosso do Sul', 'Mato Grosso', 'Goiás', 'Distrito Federal'],
      dtype=object)

### Exportação do dataframe para formato CSV

A exportação do DataFrame para o formato CSV permite a preservação dos dados processados de maneira organizada, garantindo compatibilidade com diversas plataformas e ferramentas de análise. Este procedimento facilita o compartilhamento, a reutilização e o armazenamento seguro das informações, assegurando que a estrutura e o conteúdo do DataFrame sejam mantidos de forma íntegra e consistente para análises futuras.

In [121]:
df_indigenas_pais.to_csv( ROOT / "data" / "processed" / "table" / "df_pais.csv", index=False) # Salvar o DataFrame df_indigenas_pais em um arquivo CSV
df_indigenas_regioes.to_csv( ROOT / "data" / "processed" / "table" / "df_regioes.csv", index=False) # Salvar o DataFrame df_indigenas_regioes em um arquivo CSV
df_indigenas_estados.to_csv( ROOT / "data" / "processed" / "table" / "df_estados.csv", index=False) # Salvar o DataFrame df_indigenas_estados em um arquivo CSV

## Síntese final

Com a execução de todas as etapas de pré-processamento, os dados foram devidamente tratados e organizados. As inconsistências relacionadas a múltiplos níveis de colunas foram corrigidas, os tipos de dados foram ajustados para suas naturezas apropriadas, valores nulos e registros inválidos foram removidos, e o DataFrame foi segmentado e salvo de forma estruturada. Dessa maneira, os dados encontram-se agora prontos para análises exploratórias e estatísticas precisas, garantindo confiabilidade e consistência nos resultados obtidos.

## Informações sobre os dados

1. **Dados do Universo**.  

2. **Censo Demográfico 2010**: definiu-se como indígena a pessoa residente em **Terras Indígenas** que se declarou indígena pelo quesito de cor ou raça ou pelo quesito de se considerar indígena; ou a pessoa residente **fora das Terras Indígenas** que se declarou indígena no quesito de cor ou raça. Por essa razão, o total de pessoas indígenas é superior ou igual ao total de pessoas de cor ou raça declarada indígena, nos diferentes recortes.  

3. **Censo Demográfico 2022**: definiu-se como indígena a pessoa residente em **localidades indígenas** que se declarou indígena pelo quesito de cor ou raça ou pelo quesito de se considerar indígena; ou a pessoa residente **fora das localidades indígenas** que se declarou indígena no quesito de cor ou raça. Por essa razão, o total de pessoas indígenas é superior ou igual ao total de pessoas de cor ou raça declarada indígena, nos diferentes recortes.  

4. **Localidades indígenas no Censo 2022**: foram consideradas aquelas que compõem o conjunto das **Terras Indígenas**, dos **agrupamentos indígenas** e das demais áreas de conhecida ou potencial ocupação indígena. Para mais detalhes, consultar a documentação metodológica.  

5. **Terras Indígenas no Censo 2010**: o conjunto das Terras Indígenas foi formado por aquelas que estavam na situação fundiária de **declarada, homologada, regularizada e em processo de aquisição como reserva indígena** até a data de 31 de dezembro de 2010.  

6. **Terras Indígenas no Censo 2022**: foram consideradas as Terras Indígenas **declaradas, homologadas, regularizadas ou encaminhadas como Reservas Indígenas** até 31 de julho de 2022, data de referência da pesquisa, conforme os dados da Fundação Nacional dos Povos Indígenas – FUNAI. Para mais informações, consultar a documentação metodológica.  

7. **Divisão Regional**: a utilização da **Divisão Regional do Brasil em Regiões Geográficas Imediatas e Regiões Geográficas Intermediárias (2017)** para tabulação dos resultados do Censo 2022 tem fins ilustrativos de comparabilidade das operações censitárias, devendo-se atentar para as transformações territoriais ocorridas no período intercensitário.  

8. **Amazônia Legal**: para tabulação dos resultados do Censo 2010, utilizou-se o recorte da **Amazônia Legal** divulgado pelo IBGE em 2022, considerando-se que não houve alteração na composição municipal do recorte entre os Censos. Deve-se considerar, entretanto, as transformações territoriais ocorridas no período.  

---

#### Legenda

| Símbolo       | Significado                                             | Exemplos                                                                                  |
|---------------|---------------------------------------------------------|------------------------------------------------------------------------------------------|
| `-`           | Zero absoluto, não resultante de um cálculo ou arredondamento. | Em determinado município não existem pessoas de 14 anos de idade sem instrução.          |
| `0`           | Zero resultante de um cálculo ou arredondamento.       | A inflação do feijão em determinada Região Metropolitana foi 0. Determinado município produziu 400 kg de sementes de girassol (dados em toneladas). |
| `X`           | Valor inibido para não identificar o informante.      | Determinado município só possui uma empresa produtora de cimento, logo o valor de sua produção deve ser inibido. |
| `..` ou `...` | Valor não se aplica.                                   | Não se pode obter o total da produção agrícola em determinado município quando os produtos agrícolas são contabilizados com unidades de medida distintas. |
| `A a Z` (exceto X) | Valor não disponível ou faixa de valores.        | A produção de feijão em determinado município não foi pesquisada ou determinado município não existia no ano da pesquisa; nível de precisão da produção estimada de combustíveis está na faixa A (95 a 100%). |